name: FlutterFire Firestore Converters
type: flutter
steps:
  - name: Introduction to FlutterFire and Firestore
    directory: 0_introduction_to_flutterfire_and_firestore
    has_solution: true
  - name: Read documents without type-safety
    directory: 1_read_documents_without_type_safety
    has_solution: true
  - name: Data models and Firestore converters
    directory: 2_data_models_and_firestore_converters
    has_solution: true
  - name: Create new documents
    directory: 3_create_new_document
    has_solution: true
  - name: Update or Set?
    directory: 4_update_or_set_new_data
    has_solution: true
